### ISSUE TITLE
Not compatible with feeluown 3.7.5

### ISSUE THREAD

**Issue by oldherl** [feeluown/feeluown-download#4]
Can't load the feeluown-download plugin.
OS: Arch Linux
feeluown 3.7.5-1
```
[2021-03-18 21:39:44,330 feeluown.plugin:118] [ERROR]: Enable plugin:音乐下载 failed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feeluown/plugin.py", line 116, in load_module
    self.enable(plugin)
  File "/usr/lib/python3.9/site-packages/feeluown/plugin.py", line 95, in enable
    plugin.enable(self._app)
  File "/usr/lib/python3.9/site-packages/feeluown/plugin.py", line 71, in enable
    self._module.enable(app)
  File "/home/oldherl/.local/lib/python3.9/site-packages/fuo_dl/__init__.py", line 37, in enable
    from .ui import DownloadUi  # noqa
  File "/home/oldherl/.local/lib/python3.9/site-packages/fuo_dl/ui.py", line 5, in <module>
    from feeluown.helpers import async_run
ModuleNotFoundError: No module named 'feeluown.helpers'
```

**Comment by oldherl** [comment]
#5 tries to fix this.

**Comment by oldherl** [comment]
#6 adds the button back
